### ISSUE TITLE
plugin restarts my kindle oasis with KoReader

### ISSUE THREAD

**Issue by joespinoza** [Billiam/hardcoverapp.koplugin#1]
plugin restarts my kindle oasis with KoReader every time i tried configure the plugin

**Comment by Billiam** [comment]
I don't have an oasis to test with, but:

* What version of the plugin are you using?
* Do you see any errors in koreader's `crash.log`? It's usually stored in the koreader directory.

**Comment by joespinoza** [comment]
i'm using the 0.0.4 version
[crash.log](https://github.com/user-attachments/files/17970357/crash.log)

**Comment by Billiam** [comment]
Thanks! I see an issue I missed somehow, should have a fix for that shortly.

**Comment by Billiam** [comment]
Can you try the current main branch (https://github.com/Billiam/hardcoverapp.koplugin/archive/refs/heads/main.zip) and let me know if you still have the same issue?

**Comment by joespinoza** [comment]
it's working, thanks
