### ISSUE TITLE
[Request] Auto-update based on percentage, not time

### ISSUE THREAD

**Issue by paru-de** [Billiam/hardcoverapp.koplugin#5]
Would it be possible to update progress based on the percentage read? Instead of calling the Hardcover API every n minutes, we would do so at every n% of the book read. This way, regardless of a book's length, we would send a fixed number of API calls to the Hardcover servers.

For example:

If I set my update interval to every 20 minutes, a 5-7 hour book would generate 17 to 23 requests. Meanwhile, a 40-hour book would result in 122 requests.

However, if I set auto-update to every 10% read, both books would generate exactly 11 requests:

- 1 request to set the status to "Currently reading."
- 9 requests to update the progress at each percentage milestone (10%, 20%, ..., 90%).
- 1 request to set the status to "Read" (Finished).

You would need to convert the page numbers into percentages, but I imagine that making fewer API calls would help Hardcover and also reduce clutter in the reading journal:

![image](https://github.com/user-attachments/assets/77cc58e4-2d69-4999-8309-ca97db55087c).

I tried to implement this myself, but my limited Lua knowledge (outside of nvim) and the sparse Koreader API documentation made it too challenging.

Lastly, thank you so much! I got my Kobo last week and have been reading non-stop with Koreader and your plugin. It works flawlessly and feels very intuitive to use.

**Comment by Billiam** [comment]
I like that idea :+1:

**Comment by Billiam** [comment]
Added in [v0.0.7](https://github.com/Billiam/hardcoverapp.koplugin/releases/tag/0.0.7)!

**Comment by paru-de** [comment]
Awesome, thank you so much! I'm reading through The Complete Malazan with 17k+ pages next year, and this should really come in handy 😅
